apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: {{ .Values.namespace }}
data:
  APP_NAME: {{ .Values.config.APP_NAME | quote }}
  APP_VERSION: {{ .Values.config.APP_VERSION | quote }}
  API_PREFIX: {{ .Values.config.API_PREFIX | quote }}

  HOST: {{ .Values.config.HOST | quote }}
  PORT: {{ .Values.config.PORT | quote }}

  DATABASE_NAME: {{ .Values.config.DATABASE_NAME | quote }}

  JWT_ALGORITHM: {{ .Values.config.JWT_ALGORITHM | quote }}
  JWT_ISSUER: {{ .Values.config.JWT_ISSUER | quote }}
  ACCESS_TOKEN_EXPIRE_MINUTES: {{ .Values.config.ACCESS_TOKEN_EXPIRE_MINUTES | quote }}