apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_URI: {{ .Values.secret.MONGO_URI | quote }}
  JWT_SECRET_KEY: {{ .Values.secret.JWT_SECRET_KEY | quote }}